# Проект 1. Кто хочет стать миллионером кинопроката?

## 1. У какого фильма из списка самый большой бюджет?

In [29]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies.sort_values(by = 'budget')

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
885,tt0283111,5000000,38275483,National Lampoonâ€™s Van Wilder,Ryan Reynolds|Tara Reid|Tim Matheson|Kal Penn|...,Walt Becker,Don't Graduate. Celebrate.,"Van Wilder is an outgoing, and extremely popul...",92,Comedy|Romance,Tapestry Films|Artisan Entertainment,3/29/2002,5.9,2002
1173,tt0335563,5000000,2466444,Wonderland,Val Kilmer|Dylan McDermott|Kate Bosworth|Josh ...,James Cox,"Sex, drugs, murder. Welcome to L.A.","On the afternoon of July 1, 1981, Los Angeles ...",104,Crime|Drama|Mystery|Thriller,Lions Gate Films,10/23/2003,6.4,2003
277,tt1182345,5000000,9760104,Moon,Sam Rockwell|Kevin Spacey|Dominique McElligott...,Duncan Jones,The last place you'd ever expect to find yours...,With only three weeks left in his three year c...,97,Science Fiction|Drama,Liberty Films UK|Lunar Industries|Xingu Films|...,6/12/2009,7.4,2009
1817,tt0249462,5000000,110000000,Billy Elliot,Jamie Bell|Julie Walters|Jean Heywood|Jamie Dr...,Stephen Daldry,Inside every one of us is a special talent wai...,Set against the background of the 1984 Miner's...,110,Drama|Comedy|Music,BBC Films|Tiger Aspect Productions|StudioCanal...,5/18/2000,7.1,2000
805,tt1772240,5000000,25562924,Apollo 18,Ryan Robbins|Warren Christie|Lloyd Owen|Andrew...,Gonzalo LÃ³pez-Gallego,There's a reason we've never gone back to the ...,"Officially, Apollo 17 was the last manned miss...",86,Horror|Thriller|Science Fiction,Bazelevs Production|Dimension Films|Bekmambeto...,7/20/2011,4.9,2011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,tt0401729,260000000,284139100,John Carter,Taylor Kitsch|Lynn Collins|Mark Strong|Willem ...,Andrew Stanton,Lost in Our World. Found in Another.,Civil War vet John Carter is transplanted to M...,132,Action|Adventure|Fantasy|Science Fiction,Walt Disney Pictures,3/7/2012,6.0,2012
380,tt0398286,260000000,591794936,Tangled,Zachary Levi|Mandy Moore|Donna Murphy|Ron Perl...,Nathan Greno|Byron Howard,They're taking adventure to new lengths.,When the kingdom's most wanted-and most charmi...,100,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,11/24/2010,7.3,2010
14,tt2395427,280000000,1405035767,Avengers: Age of Ultron,Robert Downey Jr.|Chris Hemsworth|Mark Ruffalo...,Joss Whedon,A New Age Has Come.,When Tony Stark tries to jumpstart a dormant p...,141,Action|Adventure|Science Fiction,Marvel Studios|Prime Focus|Revolution Sun Studios,4/22/2015,7.4,2015
1669,tt0449088,300000000,961000000,Pirates of the Caribbean: At World's End,Johnny Depp|Orlando Bloom|Keira Knightley|Geof...,Gore Verbinski,"At the end of the world, the adventure begins.","Captain Barbossa, long believed to be dead, ha...",169,Adventure|Fantasy|Action,Walt Disney Pictures|Jerry Bruckheimer Films|S...,5/19/2007,6.8,2007
723,tt1298650,380000000,1021683000,Pirates of the Caribbean: On Stranger Tides,Johnny Depp|PenÃ©lope Cruz|Geoffrey Rush|Ian M...,Rob Marshall,Live Forever Or Die Trying.,Captain Jack Sparrow crosses paths with a woma...,136,Adventure|Action|Fantasy,Walt Disney Pictures|Jerry Bruckheimer Films|M...,5/11/2011,6.3,2011

## 2-3. Какой из фильмов самый длительный/короткий (в минутах)?

In [146]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies.sort_values(by = 'runtime')

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
768,tt1449283,30000000,14460000,Winnie the Pooh,Jim Cummings|Travis Oates|Jim Cummings|Bud Luc...,Stephen Anderson|Don Hall,Oh Pooh.,"During an ordinary day in Hundred Acre Wood, W...",63,Animation|Family,Walt Disney Pictures|Walt Disney Animation Stu...,4/13/2011,6.8,2011
930,tt0280030,20000000,109862682,Return to Never Land,Harriet Owen|Blayne Weaver|Jeff Bennett|Kath S...,Robin Budd|Donovan Cook,The Classic Continues,The classic tale of 'Peter Pan' continues in D...,72,Adventure|Fantasy|Animation|Family,Walt Disney Pictures|Walt Disney Television An...,2/14/2002,6.2,2002
1097,tt0283426,20000000,135680000,The Jungle Book 2,John Goodman|Haley Joel Osment|Mae Whitman|Phi...,Steve Trenbirth,Feel the jungle beat,"Mowgli, missing the jungle and his old friends...",72,Family|Animation|Adventure,Walt Disney Pictures|Walt Disney Television An...,2/7/2003,5.6,2003
1408,tt0361089,35000000,19478106,Valiant,Ewan McGregor|Ricky Gervais|Tim Curry|Jim Broa...,Gary Chapman,"Some pigeons eat crumbs, others make history.",The animated comedy tells the story of a lowly...,76,Animation|Family|Adventure,Vanguard Films|Scanbox,3/25/2005,5.3,2005
1626,tt0299172,110000000,103951461,Home on the Range,Randy Quaid|Steve Buscemi|Judi Dench|Cuba Good...,Will Finn|John Sanford,Bust a Moo.,The Little Piece of Heaven family farm is abou...,76,Western|Animation|Family|Comedy|Music,Walt Disney Pictures|Walt Disney Feature Anima...,4/2/2004,5.8,2004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,tt0213149,140000000,449220945,Pearl Harbor,Ben Affleck|Josh Hartnett|Kate Beckinsale|Cuba...,Michael Bay,"December 7, 1941 - A day that shall live in in...",The lifelong friendship between Rafe McCawley ...,183,History|Romance|War,Jerry Bruckheimer Films|Touchstone Pictures,5/21/2001,6.6,2001
1336,tt0360717,207000000,550000000,King Kong,Naomi Watts|Jack Black|Adrien Brody|Thomas Kre...,Peter Jackson,The eighth wonder of the world.,"In 1933 New York, an overly ambitious movie pr...",187,Adventure|Drama|Action,WingNut Films|Universal Pictures|Big Primate P...,12/14/2005,6.4,2005
1736,tt0462322,67000000,25037897,Grindhouse,Kurt Russell|ZoÃ« Bell|Rosario Dawson|Vanessa ...,Robert Rodriguez|Eli Roth|Quentin Tarantino|Ed...,A double feature that'll tear you in two!,Two full length feature horror movies written ...,191,Thriller|Action|Horror,Big Talk Productions|Yer Dead Productions|Wein...,4/6/2007,6.5,2007
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003
1157,tt0279111,56000000,12923936,Gods and Generals,Stephen Lang|Jeff Daniels|Robert Duvall|Kevin ...,Ronald F. Maxwell,The nations heart was touched by...,The film centers mostly around the personal an...,214,Drama|History|War,Turner Pictures|Antietam Filmworks,2/21/2003,5.8,2003

## 4. Какова средняя длительность фильмов?

In [31]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies.runtime.mean()

109.6585494970884

##  5. Каково медианное значение длительности фильмов?

In [32]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies.runtime.median()

107.0

## 6-7. Какой фильм самый прибыльный/убыточный?

In [33]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['profit'] = movies['revenue'] - movies['budget']
movies.sort_values(by = 'profit')

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090
1616,tt0318974,145000000,25819961,The Alamo,Dennis Quaid|Billy Bob Thornton|Jason Patric|P...,John Lee Hancock,You will never forget,Based on the 1836 standoff between a group of ...,137,Western|History|War,Imagine Entertainment|Touchstone Pictures,4/7/2004,5.9,2004,-119180039
809,tt1305591,150000000,38992758,Mars Needs Moms,Seth Green|Joan Cusack|Dan Fogler|Breckin Meye...,Simon Wells,Mom needs a little space.,"When Martians suddenly abduct his mom, mischie...",88,Adventure|Animation|Family,Walt Disney Animation Studios,3/9/2011,5.5,2011,-111007242
958,tt0180052,100000000,7103973,The Adventures of Pluto Nash,Eddie Murphy|Randy Quaid|Rosario Dawson|Joe Pa...,Ron Underwood,Action's future has arrived...,"The year is 2087, the setting is the moon. Edd...",95,Action|Comedy|Science Fiction,Village Roadshow Pictures|Castle Rock Entertai...,8/15/2002,4.6,2002,-92896027
1464,tt0424095,149000000,64459316,Flushed Away,Hugh Jackman|Kate Winslet|Ian McKellen|Jean Re...,David Bowers|Sam Fell,Someone's Going Down,"London high-society mouse, Roddy is flushed do...",85,Adventure|Animation|Comedy|Family,Aardman Animations|DreamWorks Animation,10/22/2006,6.0,2006,-84540684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
970,tt0848228,220000000,1519557910,The Avengers,Robert Downey Jr.|Chris Evans|Mark Ruffalo|Chr...,Joss Whedon,Some assembly required.,When an unexpected enemy emerges and threatens...,143,Science Fiction|Action|Adventure,Marvel Studios,4/25/2012,7.3,2012,1299557910
4,tt2820852,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,Deckard Shaw seeks revenge against Dominic Tor...,137,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,4/1/2015,7.3,2015,1316249360
0,tt0369610,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,Twenty-two years after the events of Jurassic ...,124,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,6/9/2015,6.5,2015,1363528810
3,tt2488496,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,Thirty years after defeating the Galactic Empi...,136,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,7.5,2015,1868178225
239,tt0499549,237000000,2781505847,Avatar,Sam Worthington|Zoe Saldana|Sigourney Weaver|S...,James Cameron,Enter the World of Pandora.,"In the 22nd century, a paraplegic Marine is di...",162,Action|Adventure|Fantasy|Science Fiction,Ingenious Film Partners|Twentieth Century Fox ...,12/10/2009,7.1,2009,2544505847

## 8. У скольких фильмов из датасета объем сборов оказался выше бюджета?

In [36]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['profit'] = movies['revenue'] - movies['budget']
movies[movies['profit']>0].count()

imdb_id                 1478
budget                  1478
revenue                 1478
original_title          1478
cast                    1478
director                1478
tagline                 1478
overview                1478
runtime                 1478
genres                  1478
production_companies    1478
release_date            1478
vote_average            1478
release_year            1478
profit                  1478
dtype: int64

##  9. Какой фильм оказался самым кассовым в 2008 году?

In [148]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies[movies['release_year'] == 2008].sort_values(by = 'revenue').tail(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008

## 10. Самый убыточный фильм за период с 2012 по 2014 годы (включительно)?

In [151]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['profit'] = movies['revenue'] - movies['budget']
movies[(movies['release_year']>=2012)&(movies['release_year']<=2014)].sort_values(by = 'profit').head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
1245,tt1210819,255000000,89289910,The Lone Ranger,Johnny Depp|Armie Hammer|William Fichtner|Hele...,Gore Verbinski,Never Take Off the Mask,The Texas Rangers chase down a gang of outlaws...,149,Action|Adventure|Western,Walt Disney Pictures|Jerry Bruckheimer Films|I...,7/3/2013,6.0,2013,-165710090

## 11. Какого жанра фильмов больше всего?

In [152]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['genres'] = movies['genres'].str.split('|')
movies = movies.explode('genres')
movies['genres'].value_counts().head(1)

Drama    782
Name: genres, dtype: int64

## 12. Фильмы какого жанра чаще всего становятся прибыльными?

In [154]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['profit'] = movies['revenue'] - movies['budget']
movies['genres'] = movies['genres'].str.split('|')
movies = movies.explode('genres')
sorted_movies = movies[movies['profit']>0]
sorted_movies['genres'].value_counts().head(1)

Drama    560
Name: genres, dtype: int64

## 13. У какого режиссёра самые большие суммарные кассовые сборы?

In [155]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
directors = movies.groupby(['director']).sum()
directors.sort_values(by = 'revenue').tail(1)

                   budget     revenue  runtime  vote_average  release_year
director
Peter Jackson  1288000000  6490593685     1355          58.1         16059

## 14. Какой режиссер снял больше всего фильмов в стиле Action?

In [156]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['director'] = movies['director'].str.split('|')
movies = movies.explode('director')
movies[movies.genres.str.contains("Action")].director.value_counts().head(1)

Robert Rodriguez    9
Name: director, dtype: int64

## 15. Фильмы с каким актером принесли самые высокие кассовые сборы в 2012 году?

In [157]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies_sort = movies[(movies.release_year == 2012)].copy()
movies_sort['cast'] = movies_sort['cast'].str.split('|')
movies_sort = movies_sort.explode('cast')
movies_sort.groupby(['cast'])['revenue'].sum().sort_values().tail(1)

cast
Chris Hemsworth    2027450773
Name: revenue, dtype: int64

## 16. Какой актер снялся в большем количестве высокобюджетных фильмов? Примечание: в фильмах, где бюджет выше среднего по данной выборке.

In [20]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
result = pd.Series(movies[movies.budget > movies.budget.mean()].cast.str.split('|').sum()).value_counts().index[0]
print(result)

Matt Damon

## 17. В фильмах какого жанра больше всего снимался Nicolas Cage?

In [158]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['genres'] = movies['genres'].str.split('|')
movies = movies.explode('genres')
movies[movies.cast.str.contains("Nicolas Cage")].genres.value_counts().idxmax()

'Action'

## 18. Самый убыточный фильм от Paramount Pictures?

In [160]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['profit'] = movies['revenue'] - movies['budget']
movies['production_companies'] = movies['production_companies'].str.split('|')
movies = movies.explode('production_companies')
movies[movies.production_companies == "Paramount Pictures"].sort_values(by='profit').head(1)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year,profit
925,tt0267626,100000000,35168966,K-19: The Widowmaker,Harrison Ford|Liam Neeson|Peter Sarsgaard|Joss...,Kathryn Bigelow,Fate has found its hero.,When Russia's first nuclear submarine malfunct...,138,Thriller|Drama|History,Paramount Pictures,7/19/2002,6.0,2002,-64831034

## 19. Какой год стал самым успешным по суммарным кассовым сборам?

In [40]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
top_year = movies.groupby('release_year').revenue.sum().sort_values().idxmax()
print(top_year)

2015

## 20. Какой самый прибыльный год для студии Warner Bros?

In [86]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['profit'] = movies['revenue'] - movies['budget']
warner_movies = movies[movies['production_companies'].str.contains('Warner Bros')]
warner_movies.groupby('release_year')['profit'].sum().sort_values().idxmax()

2014

## 21. В каком месяце за все годы суммарно вышло больше всего фильмов?

In [44]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['release_date'] = movies['release_date'].str.split('/')
movies['month'] = movies.release_date.apply(lambda x:x[0])
final_group = movies.groupby(['month'])['original_title'].count().sort_values().idxmax()
print(final_group)

9

## 22. Сколько суммарно вышло фильмов летом (за июнь, июль, август)?

In [57]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['release_date'] = movies['release_date'].str.split('/')
movies['month'] = movies.release_date.apply(lambda x:x[0])
summer_movies = movies[(movies['month']>"5")&(movies['month']<"9")]
summer_movies['imdb_id'].nunique()

450

## 23. Для какого режиссера зима — самое продуктивное время года?

In [84]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['release_date'] = movies['release_date'].str.split('/')
movies['month'] = movies.release_date.apply(lambda x:x[0])
winter_movies = movies[(movies['month']>"11")&(movies['month']<"3")]
winter_movies['director'] = winter_movies['director'].str.split('|')
winter_movies = winter_movies.explode('director')
winter_movies.director.value_counts()

<ipython-input-84-fb4e0bdb6928>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  winter_movies['director'] = winter_movies['director'].str.split('|')

Peter Jackson        7
Steven Soderbergh    5
Clint Eastwood       5
Nancy Meyers         4
Martin Scorsese      4
                    ..
John Requa           1
Bill Condon          1
Frank Miller         1
John Musker          1
Phil Lord            1
Name: director, Length: 261, dtype: int64

## 24. Какая студия даёт самые длинные названия своим фильмам по количеству символов?

In [142]:
import pandas as pd
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['production_companies'] = movies['production_companies'].apply(lambda x: x.split(sep = '|'))
movies = movies.explode('production_companies')
movies['lenght'] = movies['original_title'].apply(lambda x: len(x))
final = movies.groupby(['production_companies'])['lenght'].max().sort_values()
display(final)

production_companies
Ixtlan Productions                         2
Global Entertainment Group                 2
XM2 Productions                            2
Berlanti Productions                       3
Everest Entertainment                      3
                                          ..
Jim Henson Company, The                   59
Walt Disney                               62
Walden Media                              62
Twentieth Century Fox Film Corporation    83
Four By Two Productions                   83
Name: lenght, Length: 1771, dtype: int64

## 25. Описания фильмов какой студии в среднем самые длинные по количеству слов?

In [133]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['total_words_in_overview'] = movies.overview.apply(lambda x: len(x.split(' ')))
movies['production_companies_list'] = movies['production_companies'].str.split('|')
movies_exploded = movies.explode('production_companies_list')
movies_exploded.groupby(['production_companies_list'])['total_words_in_overview'].mean().sort_values().idxmax()

'Midnight Picture Show'

## 26. Какие фильмы входят в один процент лучших по рейтингу?

In [119]:
import pandas as pd 
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
q99 = movies["vote_average"].quantile(0.99)
movies = movies[movies["vote_average"] > q99]
display(movies)

,imdb_id,budget,revenue,original_title,cast,director,tagline,overview,runtime,genres,production_companies,release_date,vote_average,release_year
9,tt2096673,175000000,853708609,Inside Out,Amy Poehler|Phyllis Smith|Richard Kind|Bill Ha...,Pete Docter,Meet the little voices inside your head.,"Growing up can be a bumpy road, and it's no ex...",94,Comedy|Animation|Family,Walt Disney Pictures|Pixar Animation Studios|W...,6/9/2015,8.0,2015
34,tt3170832,6000000,35401758,Room,Brie Larson|Jacob Tremblay|Joan Allen|Sean Bri...,Lenny Abrahamson,Love knows no boundaries,Jack is a young boy of 5 years old who has liv...,117,Drama|Thriller,Element Pictures|No Trace Camping|A24|Duperele...,10/16/2015,8.0,2015
118,tt0816692,165000000,621752480,Interstellar,Matthew McConaughey|Jessica Chastain|Anne Hath...,Christopher Nolan,Mankind was born on Earth. It was never meant ...,Interstellar chronicles the adventures of a gr...,169,Adventure|Drama|Science Fiction,Paramount Pictures|Legendary Pictures|Warner B...,11/5/2014,8.0,2014
119,tt2015381,170000000,773312399,Guardians of the Galaxy,Chris Pratt|Zoe Saldana|Dave Bautista|Vin Dies...,James Gunn,All heroes start somewhere.,"Light years from Earth, 26 years after being a...",121,Action|Science Fiction|Adventure,Marvel Studios|Moving Picture Company (MPC)|Bu...,7/30/2014,7.9,2014
125,tt2084970,14000000,233555708,The Imitation Game,Benedict Cumberbatch|Keira Knightley|Matthew G...,Morten Tyldum,The true enigma was the man who cracked the code.,Based on the real life story of legendary cryp...,113,History|Drama|Thriller|War,Black Bear Pictures|Bristol Automotive,11/14/2014,8.0,2014
128,tt2267998,61000000,369330363,Gone Girl,Ben Affleck|Rosamund Pike|Carrie Coon|Neil Pat...,David Fincher,You don't know what you've got 'til it's...,With his wife's disappearance having become th...,145,Mystery|Thriller|Drama,Twentieth Century Fox Film Corporation|Regency...,10/1/2014,7.9,2014
138,tt2278388,30000000,174600318,The Grand Budapest Hotel,Ralph Fiennes|Tony Revolori|F. Murray Abraham|...,Wes Anderson,A perfect holiday without leaving home.,The Grand Budapest Hotel tells of a legendary ...,99,Comedy|Drama,Fox Searchlight Pictures|Scott Rudin Productio...,2/26/2014,7.9,2014
370,tt1375666,160000000,825500000,Inception,Leonardo DiCaprio|Joseph Gordon-Levitt|Ellen P...,Christopher Nolan,Your mind is the scene of the crime.,"Cobb, a skilled thief who commits corporate es...",148,Action|Thriller|Science Fiction|Mystery|Adventure,Legendary Pictures|Warner Bros.|Syncopy,7/14/2010,7.9,2010
599,tt0468569,185000000,1001921825,The Dark Knight,Christian Bale|Michael Caine|Heath Ledger|Aaro...,Christopher Nolan,Why So Serious?,Batman raises the stakes in his war on crime. ...,152,Drama|Action|Crime|Thriller,DC Comics|Legendary Pictures|Warner Bros.|Syncopy,7/16/2008,8.1,2008
872,tt0253474,35000000,120072577,The Pianist,Adrien Brody|Thomas Kretschmann|Frank Finlay|M...,Roman Polanski,Music was his passion. Survival was his master...,The Pianist is a film adapted from the biograp...,150,Drama|War,Bac Films|Canal+Polska|Heritage Films|Studio B...,9/24/2002,7.9,2002
1081,tt0167260,94000000,1118888979,The Lord of the Rings: The Return of the King,Elijah Wood|Ian McKellen|Viggo Mortensen|Liv T...,Peter Jackson,The eye of the enemy is moving.,Aragorn is revealed as the heir to the ancient...,201,Adventure|Fantasy|Action,WingNut Films|New Line Cinema,12/1/2003,7.9,2003
1183,tt0993846,100000000,392000694,The Wolf of Wall Street,Leonardo DiCaprio|Jonah Hill|Margot Robbie|Kyl...,Martin Scorsese,EARN. SPEND. PARTY.,A New York stockbroker refuses to cooperate in...,180,Crime|Drama|Comedy,Paramount Pictures|Appian Way|EMJAG Production...,12/25/2013,7.9,2013
1191,tt2024544,20000000,187000000,12 Years a Slave,Chiwetel Ejiofor|Michael Fassbender|Lupita Nyo...,Steve McQueen,The extraordinary true story of Solomon Northup,"In the pre-Civil War United States, Solomon No...",134,Drama|History,Plan B Entertainment|Regency Enterprises|River...,10/18/2013,7.9,2013
1800,tt0209144,9000000,39723096,Memento,Guy Pearce|Carrie-Anne Moss|Joe Pantoliano|Mar...,Christopher Nolan,Some memories are best forgotten.,Suffering short-term memory loss after a head ...,113,Mystery|Thriller,Summit Entertainment|Newmarket Capital Group|T...,10/11/2000,7.9,2000

## 27. Какие актеры чаще всего снимаются в одном фильме вместе?

In [123]:
import pandas as pd
import collections
from itertools import combinations
movies = pd.read_csv('D:\Google\movie_bd_v5.csv')
movies['cast'] = movies['cast'].apply(lambda x:x.split('|'))
movies['pairs'] = movies['cast'].apply(lambda s: list(combinations(s, 2)))
movies = movies.explode('pairs')
collections.Counter(movies['pairs']).most_common(1)

[(('Daniel Radcliffe', 'Rupert Grint'), 8)]